pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'apt-get update && apt-get install -y openjdk-11-jdk'
                sh 'javac HelloWorld.java'
            }
        }

        stage('Run') {
            steps {
                sh 'java HelloWorld'
            }
        }
    }
}

