pipeline {
  agent any
  stages {
    stage('build') {
    steps {
        sh 'javac HelloWorld.jav'
      }
    }
    stage('run') {
      steps {
        sh 'java HelloWorld'
      }
    }
  }
}
    
